version: '3.8'

services:
  dev-console-cli:
    build: .
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-8080}
      - HOST=${HOST:-0.0.0.0}
    volumes:
      # Mount extension files for development
      - ./extension:/app/extension:ro
      - ./demo.html:/app/demo.html:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:' + process.env.PORT + '/api/logs', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx for serving static files and reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./demo.html:/usr/share/nginx/html/demo.html:ro
      - ./extension:/usr/share/nginx/html/extension:ro
    depends_on:
      - dev-console-cli
    restart: unless-stopped
